// Generated by https://pagedraw.io/pages/12514
import React from 'react';
import './component_2.css';


export default class Component_2 extends React.Component {
  render() {
    return (
      <div className="component_2-component_2">
          <div className="component_2-0">
              <div className="component_2-rectangle_2">
                  <div className="component_2-0-0-0">
                      <div className="component_2-another_one_-7">
                          Another one
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
