// Generated by https://pagedraw.io/pages/12514
import React from 'react';
import './component_1.css';


export default class Component_1 extends React.Component {
  render() {
    return (
      <div className="component_1-component_1">
          <div className="component_1-0">
              <div className="component_1-rectangle-2">
                  <div className="component_1-0-0-0">
                      <div className="component_1-hello_world_page_1">
                          Hello world, Page 1
                      </div>
                  </div>
              </div>
          </div>
          <div className="component_1-1">
              <input type="text" placeholder="Placeholder" className="component_1-text_input-9" /> 
          </div>
          <div className="component_1-2">
              <div className="component_1-check_box-9">
                  <input type="checkbox" checked="true" className="component_1-2-0-0" /> 
              </div>
          </div>
      </div>
    );
  }
};
